[default]
template_dir = "templates"
key = "def key"

[debug]
address = "127.0.0.1"
port = 8000
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "127.0.0.1"
port = 8000
workers = 10
keep_alive = 5
log_level = "critical"

#[global.databases]
#db = { url = "postgres://postgres:postgres@192.168.212.44/disel_test1" }

